/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ttmo_ObjectJNI */

#ifndef _Included_com_ttmo_ObjectJNI
#define _Included_com_ttmo_ObjectJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ttmo_ObjectJNI
 * Method:    getData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ttmo_ObjectJNI_getData
  (JNIEnv *, jobject);

/*
 * Class:     com_ttmo_ObjectJNI
 * Method:    setData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ttmo_ObjectJNI_setData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
