/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ttmo_HelloJNI */

#ifndef _Included_com_ttmo_HelloJNI
#define _Included_com_ttmo_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ttmo_HelloJNI
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ttmo_HelloJNI_helloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
